[project]
name = "superstore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.11.5",
    "dbt-snowflake>=1.11.2",
]
