name: cd
on:
  push:
    branches:
      - main

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up uv
        uses: astral-sh/setup-uv@5
      - name: install dependencies
        run: uv sync
      - name: run dbt
        working-directory: dbt/superstore
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: uv run dbt build --full-refresh

  docker-push:
    runs-on: ubuntu-latest
    needs: dbt-build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      # GCP auth via Workload Identity Federation
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/453807572642/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@project-2c81508f-6a88-4f9c-86d.iam.gserviceaccount.com
      - name: configure docker for artifact registry
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev
      - name: build docker image
        run: |
         docker build -t superstore-dbt .
      - name: tag and push docker image
        run: |
         docker tag superstore-dbt europe-west4-docker.pkg.dev/project-2c81508f-6a88-4f9c-86d/superstore/superstore-dbt:${{ github.sha }}
         docker tag superstore-dbt europe-west4-docker.pkg.dev/project-2c81508f-6a88-4f9c-86d/superstore/superstore-dbt:latest
         docker push europe-west4-docker.pkg.dev/project-2c81508f-6a88-4f9c-86d/superstore/superstore-dbt:${{ github.sha }}
         docker push europe-west4-docker.pkg.dev/project-2c81508f-6a88-4f9c-86d/superstore/superstore-dbt:latest